server:
  port: 9090

eureka:
  client:
    registryFetchIntervalSeconds: 5
    
security:
  basic:
    enabled: false   

management:
  security:
    enabled: false 

#fortunes:
#  ribbon:
#    ServerListRefreshInterval: 5000
#
#---
#
#spring:
#  profiles: pact
#
#ribbon:
#  eureka:
#    enabled: false

hystrix:
  command:
    randomFortune:
      execution.isolation.thread.timeoutInMilliseconds: 3000

#fortunes:
#  ribbon:
#    listOfServers: localhost:8080